name: Build tool

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build UndertaleModTool --no-restore
    - name: Publish Windows x86
      run: dotnet publish UndertaleModTool -c Release -r win-x86 --self-contained false -p:PublishSingleFile=true --output win_x86
    - name: Publish Windows x64
      run: dotnet publish UndertaleModTool -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true --output win_x64
    - name: Publish Windows ARM
      run: dotnet publish UndertaleModTool -c Release -r win-arm --self-contained false -p:PublishSingleFile=true --output win_arm
    - name: Copy external files
      run: |
        Copy-Item "README.md" -Destination "./win_x86/"
        Copy-Item "README.md" -Destination "./win_x64/"
        Copy-Item "README.md" -Destination "./win_arm/"
        Copy-Item "SCRIPTS.md" -Destination "./win_x86/"
        Copy-Item "SCRIPTS.md" -Destination "./win_x64/"
        Copy-Item "SCRIPTS.md" -Destination "./win_arm/"
    - name: Archive artifacts
      run: |
        cd win_x86
        7z -tzip a UndertaleModTool-Nightly-x86.zip * -mx0 | findstr ing
        cd ..
        cd win_x64
        7z -tzip a UndertaleModTool-Nightly-x64.zip * -mx0 | findstr ing
        cd ..
        cd win_arm
        7z -tzip a UndertaleModTool-Nightly-ARM.zip * -mx0 | findstr ing
        cd ..
        mv win_x86\UndertaleModTool-Nightly-x86.zip .
        mv win_x64\UndertaleModTool-Nightly-x64.zip .
        mv win_arm\UndertaleModTool-Nightly-ARM.zip .
    - name: Upload UndertaleModTool-Nightly-x86.zip
      uses: actions/upload-artifact@v2
      with:
        path: UndertaleModTool-Nightly-x86.zip
    - name: Upload UndertaleModTool-Nightly-x64.zip
      uses: actions/upload-artifact@v2
      with:
        path: UndertaleModTool-Nightly-x64.zip
    - name: Upload UndertaleModTool-Nightly-ARM.zip
      uses: actions/upload-artifact@v2
      with:
        path: UndertaleModTool-Nightly-ARM.zip
  Upload:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download artifacts
      uses: actions/download-artifact@v2
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: Nightly
        prerelease: true
        name: UndertaleModTool Nightly
        files: |
          UndertaleModTool-Nightly-x86.zip
          UndertaleModTool-Nightly-x64.zip
          UndertaleModTool-Nightly-ARM.zip
        body: | 
          The nightly (absolute latest) UndertaleModTool version.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
