name: Build tool

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build UndertaleModTool --no-restore
    - name: Publish Windows x86
      run: dotnet publish UndertaleModTool -c Release -r win-x86 --self-contained false -p:PublishSingleFile=true --output win_x86
    - name: Publish Windows x64
      run: dotnet publish UndertaleModTool -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true --output win_x64
    - name: Publish Windows ARM
      run: dotnet publish UndertaleModTool -c Release -r win-arm --self-contained false -p:PublishSingleFile=true --output win_arm
    - name: Copy external files
      run: |
        Copy-Item "README.md" -Destination "./win_x86/"
        Copy-Item "README.md" -Destination "./win_x64/"
        Copy-Item "README.md" -Destination "./win_arm/"
        Copy-Item "SCRIPTS.md" -Destination "./win_x86/"
        Copy-Item "SCRIPTS.md" -Destination "./win_x64/"
        Copy-Item "SCRIPTS.md" -Destination "./win_arm/"
    - name: Archive win_x86
      uses: actions/upload-artifact@v2
      with:
        name: win_x86
        path: win_x86
    - name: Archive win_x64
      uses: actions/upload-artifact@v2
      with:
        name: win_x64
        path: win_x64
    - name: Archive win_arm
      uses: actions/upload-artifact@v2
      with:
        name: win_arm
        path: win_arm
  Upload:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download artifacts
      uses: actions/download-artifact@v2
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: Nightly
        prerelease: true
        name: UndertaleModTool Nightly
        files: |
          win_x86
          win_x64
          win_arm
        body: | 
          The nightly (absolute latest) UndertaleModTool version.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
